/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupproject;

/**
 *
 * @author Asa
 */
public class ChatroomGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChatroomGUI
     */
    public ChatroomGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DExistingLogin = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginUsername = new javax.swing.JTextField();
        LoginPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ExistingLogin = new javax.swing.JButton();
        ExistingCancel = new javax.swing.JButton();
        DGuestLogin = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        BGuestLogin = new javax.swing.JButton();
        GuestUsername = new javax.swing.JTextField();
        GuestCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DNewUser = new javax.swing.JDialog();
        lblNewUsername = new javax.swing.JLabel();
        lblNewPassword = new javax.swing.JLabel();
        lblNewPasswordConfirm = new javax.swing.JLabel();
        NewUsername = new javax.swing.JTextField();
        NewPassword = new javax.swing.JTextField();
        NewConfirmPassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BCreate = new javax.swing.JButton();
        NewCancel = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        WrongLogin = new javax.swing.JOptionPane();
        WrongInfo = new javax.swing.JOptionPane();
        Banned = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Chatbox = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Message = new javax.swing.JTextArea();
        Send = new javax.swing.JButton();
        LoginBar = new javax.swing.JMenuBar();
        Login = new javax.swing.JMenu();
        MenuMember = new javax.swing.JMenuItem();
        MenuGuest = new javax.swing.JMenuItem();
        MenuCreate = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        LoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUsernameActionPerformed(evt);
            }
        });

        LoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPasswordActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Login to get into chat!");

        ExistingLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ExistingLogin.setText("Login");
        ExistingLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExistingLoginActionPerformed(evt);
            }
        });

        ExistingCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ExistingCancel.setText("Cancel");
        ExistingCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExistingCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DExistingLoginLayout = new javax.swing.GroupLayout(DExistingLogin.getContentPane());
        DExistingLogin.getContentPane().setLayout(DExistingLoginLayout);
        DExistingLoginLayout.setHorizontalGroup(
            DExistingLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DExistingLoginLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(DExistingLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DExistingLoginLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DExistingLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(DExistingLoginLayout.createSequentialGroup()
                            .addComponent(ExistingLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExistingCancel))
                        .addGroup(DExistingLoginLayout.createSequentialGroup()
                            .addGroup(DExistingLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(DExistingLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LoginPassword)
                                .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38))
        );
        DExistingLoginLayout.setVerticalGroup(
            DExistingLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DExistingLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DExistingLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(DExistingLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DExistingLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExistingLogin)
                    .addComponent(ExistingCancel))
                .addGap(49, 49, 49))
        );

        DExistingLoginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LoginPassword, LoginUsername});

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Enter in a username ");

        BGuestLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BGuestLogin.setText("Guest Login");
        BGuestLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuestLoginActionPerformed(evt);
            }
        });

        GuestUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        GuestCancel.setText("Cancel");
        GuestCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestCancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("(with limited privileges)");

        javax.swing.GroupLayout DGuestLoginLayout = new javax.swing.GroupLayout(DGuestLogin.getContentPane());
        DGuestLogin.getContentPane().setLayout(DGuestLoginLayout);
        DGuestLoginLayout.setHorizontalGroup(
            DGuestLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DGuestLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DGuestLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(BGuestLogin)
                    .addComponent(GuestUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuestCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DGuestLoginLayout.setVerticalGroup(
            DGuestLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DGuestLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(GuestUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BGuestLogin)
                .addGap(18, 18, 18)
                .addComponent(GuestCancel)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblNewUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewUsername.setText("Username");

        lblNewPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewPassword.setText("Password");

        lblNewPasswordConfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNewPasswordConfirm.setText("Confirm Password");

        NewUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUsernameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Create your new account!");

        BCreate.setText("Create");
        BCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCreateActionPerformed(evt);
            }
        });

        NewCancel.setText("Cancel");
        NewCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCancelActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Name");

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress.setText("Address");

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAge.setText("Age");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmail.setText("Email");

        javax.swing.GroupLayout DNewUserLayout = new javax.swing.GroupLayout(DNewUser.getContentPane());
        DNewUser.getContentPane().setLayout(DNewUserLayout);
        DNewUserLayout.setHorizontalGroup(
            DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DNewUserLayout.createSequentialGroup()
                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DNewUserLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DNewUserLayout.createSequentialGroup()
                                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNewPasswordConfirm)
                                    .addComponent(lblNewUsername)
                                    .addComponent(lblNewPassword)
                                    .addComponent(lblName)
                                    .addComponent(lblAddress)
                                    .addComponent(lblAge)
                                    .addComponent(lblEmail))
                                .addGap(18, 18, 18)
                                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(NewConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(NewUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(Name)
                                    .addComponent(Address)
                                    .addComponent(Age)
                                    .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(DNewUserLayout.createSequentialGroup()
                                .addComponent(BCreate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NewCancel))))
                    .addGroup(DNewUserLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        DNewUserLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {NewConfirmPassword, NewPassword, NewUsername});

        DNewUserLayout.setVerticalGroup(
            DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DNewUserLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(DNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCreate)
                    .addComponent(NewCancel))
                .addGap(29, 29, 29))
        );

        DNewUserLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Address, Age, Email, Name, NewConfirmPassword, NewPassword, NewUsername});

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Chatbox.setEditable(false);
        Chatbox.setColumns(20);
        Chatbox.setLineWrap(true);
        Chatbox.setRows(5);
        jScrollPane1.setViewportView(Chatbox);

        Message.setColumns(20);
        Message.setRows(5);
        Message.setEnabled(false);
        jScrollPane4.setViewportView(Message);

        Send.setText("Send");
        Send.setEnabled(false);

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        MenuMember.setText("Member Login");
        MenuMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMemberActionPerformed(evt);
            }
        });
        Login.add(MenuMember);

        MenuGuest.setText("Guest Login");
        MenuGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGuestActionPerformed(evt);
            }
        });
        Login.add(MenuGuest);

        MenuCreate.setText("Create Member");
        MenuCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCreateActionPerformed(evt);
            }
        });
        Login.add(MenuCreate);

        LoginBar.add(Login);

        jMenu2.setText("Logout");
        LoginBar.add(jMenu2);

        setJMenuBar(LoginBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(Send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Send)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginUsernameActionPerformed

    private void LoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPasswordActionPerformed

    private void ExistingCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExistingCancelActionPerformed
        DExistingLogin.dispose();
    }//GEN-LAST:event_ExistingCancelActionPerformed

    private void BGuestLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuestLoginActionPerformed
        WrongInfo.showMessageDialog(this, "Enter In Real Errors later");
    }//GEN-LAST:event_BGuestLoginActionPerformed

    private void GuestCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestCancelActionPerformed
        DGuestLogin.dispose();
    }//GEN-LAST:event_GuestCancelActionPerformed

    private void ExistingLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExistingLoginActionPerformed
        // TODO add your handling code here:
        WrongLogin.showMessageDialog(this,"Wrong Username or Password");
        
    }//GEN-LAST:event_ExistingLoginActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        
    }//GEN-LAST:event_LoginActionPerformed

    private void MenuMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMemberActionPerformed
        DExistingLogin.pack();
        DExistingLogin.setSize(345,255);
        DExistingLogin.setVisible(true);
    }//GEN-LAST:event_MenuMemberActionPerformed

    private void MenuGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGuestActionPerformed
        DGuestLogin.pack();
        DGuestLogin.setSize(215,255);
        DGuestLogin.setVisible(true);
    }//GEN-LAST:event_MenuGuestActionPerformed

    private void NewUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUsernameActionPerformed

    private void NewCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCancelActionPerformed
        DNewUser.dispose();
    }//GEN-LAST:event_NewCancelActionPerformed

    private void MenuCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCreateActionPerformed
        DNewUser.pack();
        DNewUser.setSize(355,500);
        DNewUser.setVisible(true);
    }//GEN-LAST:event_MenuCreateActionPerformed

    private void BCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCreateActionPerformed
        WrongInfo.showMessageDialog(this, "Enter In Real Errors later");
    }//GEN-LAST:event_BCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatroomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatroomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatroomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatroomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatroomGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Age;
    private javax.swing.JButton BCreate;
    private javax.swing.JButton BGuestLogin;
    private javax.swing.JOptionPane Banned;
    private javax.swing.JTextArea Chatbox;
    private javax.swing.JDialog DExistingLogin;
    private javax.swing.JDialog DGuestLogin;
    private javax.swing.JDialog DNewUser;
    private javax.swing.JTextField Email;
    private javax.swing.JButton ExistingCancel;
    private javax.swing.JButton ExistingLogin;
    private javax.swing.JButton GuestCancel;
    private javax.swing.JTextField GuestUsername;
    private javax.swing.JMenu Login;
    private javax.swing.JMenuBar LoginBar;
    private javax.swing.JTextField LoginPassword;
    private javax.swing.JTextField LoginUsername;
    private javax.swing.JMenuItem MenuCreate;
    private javax.swing.JMenuItem MenuGuest;
    private javax.swing.JMenuItem MenuMember;
    private javax.swing.JTextArea Message;
    private javax.swing.JTextField Name;
    private javax.swing.JButton NewCancel;
    private javax.swing.JTextField NewConfirmPassword;
    private javax.swing.JTextField NewPassword;
    private javax.swing.JTextField NewUsername;
    private javax.swing.JButton Send;
    private javax.swing.JOptionPane WrongInfo;
    private javax.swing.JOptionPane WrongLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblNewPasswordConfirm;
    private javax.swing.JLabel lblNewUsername;
    // End of variables declaration//GEN-END:variables
}
